# Generated by Django 5.0.7 on 2024-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0002_myuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="force_change_password",
            field=models.BooleanField(default=False),
        ),
    ]
